#NOVA MODIFICAÇÃO.
#ATUALIZAÇÃO 0.0.15
#ADICIONANDO O CAMPO 'asset_id' PARA QUE A JTABLE POSSA TRABALHAR COM ACL.

ALTER TABLE `#__olamundo` ADD COLUMN `asset_id` INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER `id`;

