#NOVA MODIFICAÇÃO.
#ATUALIZAÇÃO 0.0.6.
#CRIAR O BANCO DE DADOS.

#NOTE O CARACTERE '#__', ISSO É UM CARACTERE CURINGA QUE SERÁ SUBSTITUÍDO PELO PREFIXO PADRÃO DA TABELA DO BANCO
#DE DADOS EM QUE O COMPONENTE SERÁ INSTALADO.

DROP TABLE IF EXISTS `#__olamundo`;

CREATE TABLE `#__olamundo` (

	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`texto` VARCHAR(255) NOT NULL,
	`published` tinyint(4) NOT NULL DEFAULT '1',
	PRIMARY KEY(`id`)

) DEFAULT CHARSET = utf8;

INSERT INTO `#__olamundo` (`texto`) VALUES
('Olá mundo!'), ('Até mais mundo!'); 
