#NOVA MODIFICAÇÃO.
#ATUALIZAÇÃO 0.0.24.
#CRIAR OS CAMPOS QUE SERÃO UTILIZADOS PARA FAZER A CHECKAGEM DE UM REGISTRO.

#CAMPO QUE ARMAZENARÁ O ID DO USUÁRIO QUE FEZ O CHECKOUT.
ALTER TABLE `#__olamundo` ADD `checked_out` INT(10) NOT NULL DEFAULT '0' AFTER `created_by`;

#CAMPO QUE ARMAZENARÁ A TEMPO/DATA DO CHECKOUT.
ALTER TABLE `#__olamundo` ADD `checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' AFTER `checked_out`;