#NOVA MODIFICAÇÃO.
#ATUALIZAÇÃO 0.0.18.
#CRIAR DOIS NOVOS CAMPOS (LATITUDE E LONGITUDE)
#ESSES CAMPOS SERÃO RESPONSÁVEIS PARA MOSTRAR O PONTO DE UM MAPA.

ALTER TABLE `#__olamundo` ADD `latitude` DECIMAL(9,7) NOT NULL DEFAULT 0.0;
ALTER TABLE `#__olamundo` ADD `longitude` DECIMAL(10, 7) NOT NULL DEFAULT 0.0;
