#NOVA MODIFICAÇÃO
#ATUALIZAÇÃO 0.0.16
#CRIAR DOIS NOVOS CAMPOS QUE ARMAZENARÁ A DATA DE CRIAÇÃO DO REGITRO NO FORMULÁRIO E O ID DE QUEM CRIOU

ALTER TABLE `#__olamundo` ADD COLUMN `created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' AFTER `asset_id`;
ALTER TABLE `#__olamundo` ADD COLUMN `created_by` INT(10) NOT NULL DEFAULT '0' AFTER `created`;