#NOVA MODIFICAÇÃO.
#ATUALIZAÇÃO 0.0.16.
#CRIAR UM NOVO CAMPO DO TIPO DATETIME PARA ARMAZENAR A DATA E O TEMPO QUE O USUÁRIO CRIOU DETERMINADA MENSAGEM.
#CRIAR UM NOVO CAMPO DO TIPO INT PARA INFORMAR QUAL FOI O USUÁRIO QUE CRIOU A MENSAGEM.

ALTER TABLE `#__olamundo` ADD `created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00' AFTER `asset_id`;
ALTER TABLE `#__olamundo` ADD `created_by` INT(10) UNSIGNED NOT NULL DEFAULT '0' AFTER `created`;