#NOVA MODIFICAÇÃO
#ATUALIZAÇÃO 0.0.18
#ADICIONAR DOIS NOVOS CAMPOS AO BANCO DE DADOS INFORMANDO A LATITUDE E A LONGITUDE PARA CONFIGURAÇÃO DO MAPA.

ALTER TABLE `#__olamundo` ADD COLUMN `latitude` DECIMAL(9, 7) NOT NULL DEFAULT 0.0;
ALTER TABLE `#__olamundo` ADD COLUMN `longitude` DECIMAL(10, 7) NOT NULL DEFAULT 0.0;
